FROM php:8.3-fpm

RUN apt-get update && apt-get install -y mc git libpng-dev libzip-dev
# RUN apt-get install -y libssh2-1 libssh2-1-dev
# RUN pecl install ssh2

RUN cd /tmp && \
    git clone https://github.com/xdebug/xdebug.git && \
    cd xdebug && \
    git checkout xdebug_3_3 && \
    phpize && \
    ./configure --enable-xdebug && \
    make && \
    make install && \
    rm -rf /tmp/xdebug

COPY xdebug.ini /usr/local/etc/php/conf.d/

RUN docker-php-ext-install mysqli pdo pdo_mysql gd zip && docker-php-ext-enable mysqli && docker-php-ext-enable xdebug 
# RUN docker-php-ext-enable ssh2

RUN usermod -u 1000 www-data && groupmod -g 1000 www-data
RUN mkdir /var/log/php-fpm && chown www-data:www-data /var/log/php-fpm
RUN mkdir -p /var/log/app && chown www-data:www-data /var/log/app
RUN mkdir -p /usr/share/tool && chown www-data:www-data /usr/share/tool

RUN curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php && \
    php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

# RUN mkdir /root/.ssh
# COPY config /root/.ssh

WORKDIR /usr/share/nginx